server:
  port: 8080


spring:
  profiles:
    active: test
  mvc: # 关闭默认图标
    favicon:
      enabled: false
  security:
    user:
      password: 123
#  datasource:
#    username: root
#    password: 123
#    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

debug: false



person:
  name: lulu
  age: 3
  happy: true
  birth: 1999/01/01
  email: luluyang@tju.edu.cn
  mapp: {k1: v1, k2: v2}
  lis:
    - 1
    - 2
    - 3
  dog:
    name: mie
    age: 2

